version: '3'

services:

    db:
        image: mysql
        ports:
            - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: 637423
          MYSQL_DATABASE: conectivo_conecta_db # create db by default
