export const SEND_USER_INFORMATION_SUCCESS = "SEND_USER_INFORMATION_SUCCESS";
export const SEND_USER_INFORMATION_FAILURE = "SEND_USER_INFORMATION_FAILURE";
export const SEND_USER_INFORMATION_REQUEST = "SEND_USER_INFORMATION_REQUEST";
export const CREATE_USER_INFORMATION_SUCCESS = "CREATE_USER_INFORMATION_SUCCESS";
export const CREATE_USER_INFORMATION_FAILURE = "CREATE_USER_INFORMATION_FAILURE";
export const CREATE_USER_INFORMATION_REQUEST = "CREATE_USER_INFORMATION_REQUEST";
export const CHANGE_LOGIN_PAGE = "CHANGE_LOGIN_PAGE";