export const SEND_USER_INFORMATION_SUCCESS = "SEND_USER_INFORMATION_SUCCESS";
export const SEND_USER_INFORMATION_FAILURE = "SEND_USER_INFORMATION_FAILURE";
export const SEND_USER_INFORMATION_REQUEST = "SEND_USER_INFORMATION_REQUEST";