version: '3'

services:
  conectivo-db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: conectivo_conecta_db # create db by default
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  conectivo-backend:
    build:
      context: back-end/
    ports:
      - 8080:8080
    environment:
      DB_HOST: codigo_db_1
    depends_on:
      - conectivo-db

  conectivo-frontend:
    build:
      context: new-front-end/
    ports:
      - 80:80
    depends_on:
      - conectivo-backend
