version: '3'

services:

    db:
        image: mysql
        ports:
            - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: 637423
          MYSQL_DATABASE: conectivo_conecta_db # create db by default
        

    conectivo-backend:
        build:
            context: conectivo-backend/
        ports:
            - 8000:8000
        depends_on:
            - mysql

    # conectivo-frontend:
    #     build:
    #         context: conectivo-backend/
    #     ports:
    #         - 80:3000
    #     depends_on:
    #         - conectivo-backend
